### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by Gwencong** [DIVE128/DMVSNet#2]
Thank you for your excellent work! I would like to ask if the pretrained model provided is for DTU dataset or Tanks dataset. I have tried to test it on Tanks dataset, but the depth obtained seems to be not accurate

**Comment by DIVE128** [comment]
Thank you for your attention. The model provided is for DTU dataset.

**Comment by cv-lab-x** [comment]
> Thank you for your attention. The model provided is for DTU dataset.

could you provide finetune model on blendmvs ? @DIVE128
