### ISSUE TITLE
PROB_VOLUME

### ISSUE THREAD

**Issue by wln19** [DIVE128/DMVSNet#4]
Thank you for your great work. I noticed that the author proposed using double depth and estimated two probability bodies. I would like to ask why the shape of the probability body is defined as (B, 4, D, H, W) instead of (B, 2, D, H, W)

**Comment by DIVE128** [comment]
The key of the article is generating saddle cells, which is a chicken-egg problem. Dual-depth is proposed so that the geometry of the depth map converges to a saddle cell, and every 2 channels can be viewed as a group to produce dual-depth.

**Comment by wln19** [comment]
Thank you very much for your answer. I noticed that when the cost volume is regularized in the code, the final prob channel is 2. I would like to ask why it is generated like this, because we usually directly generate 1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIVE128/DMVSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIVE128/DMVSNet] PROB_VOLUME (Issue #4)





 
The key of the article is generating saddle cells, which is a chicken-egg problem. Dual-depth is proposed so that the geometry of the depth map converges to a saddle cell, and every 2 channels can be viewed as a group to produce dual-depth.
